### ISSUE TITLE
Messages blank

### ISSUE THREAD

**Issue by FJerusalem** [Againstreality/Rocket.Chat.check_mk-integration#1]
Only getting empty response from Script (using check_mk RAW 1.5.0p11):

![grafik](https://user-images.githubusercontent.com/17353814/51109251-fa481d80-17f4-11e9-9f36-47cd97515468.png)

What am I missing?

**Comment by Againstreality** [comment]
We are running in the same Issue with the new Check_mk Version. I give you an update when we have an new Version

**Comment by Againstreality** [comment]
@FJerusalem fixted it Thanks for that.
#3
